version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www
    depends_on:
      - db
    networks:
      - backend
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    expose:
      - 9000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - frontend
    expose:
      - 3000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - client
    networks:
      - frontend
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend:
